chef:
    server:
        install_script: https://raw.githubusercontent.com/rcbops/support-tools/master/chef-install/install-chef-server.sh
        install_dir: /opt/rcbops
        upgrade_dir: /opt/upgrade
    client:
        version: 11.08.0
        run_cmd: "chef-client"
environments:
    ceilometer:
        default:
             enabled: True
    openssh:
        server:
            subsystem: "sftp internal-sftp"
    package_component:
        default: havana
    keystone:
        default:
            admin_user: admin
            users:
                demo:
                    roles:
                        Member:
                          - demo
                    default_tenant: demo
                    password: secrete
                demo2:
                    roles:
                        Member:
                          - demo2
                    default_tenant: demo2
                    password: secrete
                admin:
                    roles:
                        admin:
                            - admin
                    default_tenant: admin
                    password: secrete
            tenants:
                - admin
                - service
                - demo
                - demo2
    monitoring:
        default:
            procmon_provider: monit
    mysql:
        default:
            root_network_acl: "%"
            allow_remote_root: true
    nova:
        quantum:
            apply_patches: false
            libvirt:
                virt_type: qemu
            network:
                provider: quantum
        neutron:
            apply_patches: false
            libvirt:
                virt_type: qemu
            network:
                provider: neutron
    osops:
        default:
            apply_patches: true
    horizon:
        neutron:
          enable_lb: true
        default:
            theme: default
    developer_mode:
        default:
            default: false
    osops_networks:
        management: 192.168.4.0/24
        nova: 192.168.4.0/24
        public: 192.168.4.0/24
    glance:
        default:
            image_upload: true
            images:
                - cirros
                - precise
        cf:
            api:
                default_store: swift
                swift_store_user: <Tenant_Id>:<Tenant_Name>
                swift_store_key: <Tenant_Password>
                swift_store_auth_version: "2"
                swift_store_auth_address: https://identity.api.rackspacecloud.com/v2.0
                swift_store_region: DFW
            image_upload: true
            images:
                - cirros
                - precise
    neutron:
        quantum:
            ovs:
                network_type: gre
        neutron:
            lbaas:
                enabled: true
            ovs:
                network_type: gre
    cinder:
        local:
            storage:
                provider: lvm
                lvm:
                    volume_group: vg_storage
    vips:
        mysql-db: 192.168.4.151
        rabbitmq-queue: 192.168.4.152
        cinder-api: 192.168.4.153
        glance-api: 192.168.4.153
        glance-registry: 192.168.4.153
        horizon-dash: 192.168.4.153
        horizon-dash_ssl: 192.168.4.153
        keystone-admin-api: 192.168.4.153
        keystone-internal-api: 192.168.4.153
        keystone-service-api: 192.168.4.153
        nova-api: 192.168.4.153
        nova-ec2-public: 192.168.4.153
        nova-api-metadata: 192.168.4.153
        nova-novnc-proxy: 192.168.4.153
        nova-xvpvnc-proxy: 192.168.4.153
        neutron-api: 192.168.4.153
        quantum-api: 192.168.4.153
        swift-proxy: 192.168.4.153
        ceilometer-api: 192.168.4.153
        ceilometer-central-agent: 192.168.4.153
        heat-api: 192.168.4.153
        heat-api-cfn: 192.168.4.153
        heat-api-cloudwatch: 192.168.4.153
        config:
            192.168.4.155:
                vrid: 14
                network: public
            192.168.4.156:
                vrid: 15
                network: public
            192.168.4.157:
                vrid: 16
                network: public
    bridge_devices:
        data: vmnet
        management: mgmt
rcbops:
    retrofit:
        supported:
            os:
                - ubuntu
        git:
            url: https://github.com/Apsu/retrofit.git
            branches:
                - master
                - dev
    compute:
        kernel:
          centos:
            image: ce44b9c0-bb94-4fac-a7df-99b6aeab4c57
            version: 2.6.32-358.123.2.openstack.el6.x86_64
            install: rpm -Uvh http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-2.6.32-358.123.2.openstack.el6.x86_64.rpm http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-firmware-2.6.32-358.123.2.openstack.el6.noarch.rpm http://repos.fedorapeople.org/repos/openstack/openstack-grizzly/epel-6/kernel-headers-2.6.32-358.123.2.openstack.el6.x86_64.rpm
        git:
            url: https://github.com/rcbops/chef-cookbooks.git
            branches:
                havana:
                    - v4.2.2
                    - v4.2.1
                    - v4.2.0
                grizzly:
                    - v4.1.5rc
                    - v4.1.4rc
                    - v4.1.3
                    - v4.1.2
                    - v4.1.1
                    - v4.1.0
                    - v4.0.0
                folsom:
                    - v3.0.0
                    - v3.0.1
                    - v3.1.0
        chefserver:
            run_list: []
        compute:
            run_list: ['role[single-compute]']
        ldap:
            run_list: ['role[qa-openldap]']
        controller1:
            run_list: ['role[ha-controller1]']
        controller2:
            run_list: ['role[ha-controller2]']
        cinder:
            run_list: ['role[cinder-volume]']
        network:
            run_list: ['role[single-network-node]']
        tempest:
            run_list: ['recipe[tempest]']
        orchestration1:
            run_list: ['role[heat-all]']
        orchestration2:
            run_list: ['role[heat-api]',
                       'role[heat-api-cfn]',
                       'role[heat-api-cloudwatch]']
        networkmanager:
            run_list: ['role[quantum-network-manager]']
        metrics:
            controller:
                run_list: ['role[ceilometer-setup]',
                           'role[ceilometer-api]',
                           'role[ceilometer-central-agent]',
                           'role[ceilometer-collector]']
            compute:
                run_list: ['role[ceilometer-compute]']
    storage:
        git:
            url: https://github.com/rcbops-cookbooks/swift-private-cloud.git
            branches:
                master:
                    tags:
                        - v4.2.0
        chefserver:
            run_list: []
        controller1:
            run_list: ['role[spc-starter-controller]']
        proxy:
            run_list: ['role[spc-starter-proxy]']
        storage:
            run_list: ['role[spc-starter-storage]']
tests:
  tempest:
    repo: https://github.com/openstack/tempest.git
    dir: "/opt/tempest"
    test_map:
      glance:
        - image
        - compute/images
      nova:
        - compute
      keystone:
        - compute/admin
        - compute/security_groups
        - compute/test_authorization.py
        - identity
      neutron:
        - network
      cinder:
        - compute/volumes
        - volume
      swift:
        - object_storage
rackspace:
    run_list:
    images:
        ubuntu: Ubuntu 12.04 LTS (Precise Pangolin)
        centos: centos-rdo
    flavors:
        512MB: 512MB Standard Instance
        1GB: 1GB Standard Instance
        2GB: 2GB Standard Instance
        4GB: 4GB Standard Instance
        8GB: 8GB Standard Instance
        15GB: 15GB Standard Instance
        30GB: 30GB Standard Instance
        1GBP: 1 GB Performance
        2GBP: 2 GB Performance
        4GBP: 4 GB Performance
        8GBP: 8 GB Performance
        120GBP: 120 GB Performance
        15GBP: 15 GB Performance
        30GBP: 30 GB Performance
        60GBP: 60 GB Performance
        90GBP: 90 GB Performance
    roles:
      chefserver: 1GBP
      controller: 2GBP
      compute: 8GBP
      cinder: 1GBP
    networks:
        - public
        - private
        - vmnet
        - mgmt
    network:
        vmnet:
            cidr: 192.168.3.0/24
            iface: eth2
        mgmt:
            cidr: 192.168.4.0/24
            iface: eth3
upgrade:
  commands:
    backup-db: bash <(curl -s https://raw.github.com/rcbops/support-tools/master/havana-tools/database_backup.sh)
    restore-db: bash <(curl -s https://raw.github.com/rcbops/support-tools/master/havana-tools/quantum-upgrade.sh)
    stop-services: for i in `monit status | grep Process | awk '{print $2}' | grep -v mysql | sed "s/'//g"`; do monit stop $i; done; service keepalived stop
    start-services: for i in `monit status | grep Process | awk '{print $2}' | grep -v mysql | sed "s/'//g"`; do monit start $i; done; service keepalived restart
  supported:
    v4.1.2:
      - v4.1.3rc
      - v4.1.3
      - v4.1.4rc
      - v4.1.4
      - v4.1.5rc
      - v4.1.5
    v4.1.3:
      - v4.1.4rc
      - v4.1.4
      - v4.2.1rc
      - v4.2.1
      - v4.2.2rc
      - v4.2.2
      - v4.1.5rc
      - v4.1.5
    v4.1.4:
      - v4.1.5rc
      - v4.1.5
      - v4.2.1rc
      - v4.2.1
      - v4.2.2rc
      - v4.2.2
    v4.1.5:
      - v4.2.2rc
      - v4.2.2
    v4.2.1:
      - v4.2.2rc
      - v4.2.2
    v4.2.2rc:
      - v4.2.3rc
      - v4.2.3
